version = 0.1

[default.deploy.parameters]
stack_name = "surl-app"
s3_bucket = "surl-deploy-bucket-unique-name"
s3_prefix = "surl-app"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = false
image_repositories = []

[default.global.parameters]
region = "ap-northeast-2"