version = 0.1

[default.deploy.parameters]
stack_name = "surl-app"
s3_bucket = "surl-deploy-bucket-unique-name"
s3_prefix = "surl-app"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-northeast-2"
